config/routes.rb
Inputtest2::Application.routes.draw do
  resources :recipes, :has_many => :steps
  resources :steps, :belongs_to => :recipes

  resources :recipes do
    resources :steps
  end

  resources :plugin_calls do
    resources :steps
  end

  resources :plugin_calls do
    resources :plugin_call_fields
  end

  resources :plugin_call_fields

  resources :form_handlers

  root to: "recipes#create"

end

app/models/plugin_call_field.rb
class PluginCallField < ActiveRecord::Base
  attr_accessible :field_type, :name, :required, :plugin_call_id
  belongs_to :plugin_call
end

app/controllers/plugin_call_fields_controller.rb
class PluginCallFieldsController < ApplicationController
  before_action :set_plugin_call_field, only: [:show, :edit, :update, :destroy]

  # GET /plugin_call_fields
  # GET /plugin_call_fields.json
  def index
    @plugin_call_fields = PluginCallField.all
  end

  # GET /plugin_call_fields/1
  # GET /plugin_call_fields/1.json
  def show
  end

  # GET /plugin_call_fields/new
  def new
    @plugin_call_field = PluginCallField.new
  end

  # GET /plugin_call_fields/1/edit
  def edit
  end

  # POST /plugin_call_fields
  # POST /plugin_call_fields.json
  def create
    @plugin_call = PluginCall.find(params[:plugin_call_id])
    @plugin_call_field = @plugin_call.plugin_call_fields.new(plugin_call_field_params)

    respond_to do |format|
      if @plugin_call_field.save
        format.html { redirect_to @plugin_call_field, notice: 'Plugin call field was successfully created.' }
        format.json { render action: 'show', status: :created, location: @plugin_call_field }
      else
        format.html { render action: 'new' }
        format.json { render json: @plugin_call_field.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /plugin_call_fields/1
  # PATCH/PUT /plugin_call_fields/1.json
  def update
    respond_to do |format|
      if @plugin_call_field.update(plugin_call_field_params)
        format.html { redirect_to @plugin_call_field, notice: 'Plugin call field was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @plugin_call_field.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /plugin_call_fields/1
  # DELETE /plugin_call_fields/1.json
  def destroy
    @plugin_call_field.destroy
    respond_to do |format|
      format.html { redirect_to plugin_call_fields_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_plugin_call_field
      @plugin_call_field = PluginCallField.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def plugin_call_field_params
      params[:plugin_call_field]
    end
end

app/views/plugin_call_fields/_form.html.erb
<%= simple_form_for [plugin_call, plugin_call.fields.build], :html => { :multipart => true, :class => 'form-inline' } do |f| %>

<div class="form-inputs">
  <%= f.select :field_type, %w{text_field text_area check_box file_field step_field} %>
  <%= f.text_field :name, placeholder: 'field_name' %>
  <%= f.check_box :required %><%= f.label :required %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/plugin_call_fields/edit.html.erb
<h1>Editing plugin_call_field</h1>

<%= render 'form' %>

<%= link_to 'Show', @plugin_call_field %> |
<%= link_to 'Back', plugin_call_fields_path %>

app/views/plugin_call_fields/index.html.erb
<h1>Listing plugin_call_fields</h1>

<table>
  <thead>
    <tr>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @plugin_call_fields.each do |plugin_call_field| %>
      <tr>
	<td><%= plugin_call_field.name %></td>
        <td><%= link_to 'Show', plugin_call_field %></td>
        <td><%= link_to 'Edit', edit_plugin_call_field_path(plugin_call_field) %></td>
        <td><%= link_to 'Destroy', plugin_call_field, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Plugin call field', new_plugin_call_field_path %>

app/views/plugin_call_fields/new.html.erb
<h1>New plugin_call_field</h1>

<%= render 'form2' %>

<%= link_to 'Back', plugin_call_fields_path %>

app/views/plugin_call_fields/show.html.erb
<p id="notice"><%= notice %></p>
<%= @plugin_call_field.field_type %>
<%= @plugin_call_field.name %>
<%= @plugin_call_field.test %>
<%= link_to 'Edit', edit_plugin_call_field_path(@plugin_call_field) %> |
<%= link_to 'Back', plugin_call_fields_path %>