config/routes.rb
Inputtest2::Application.routes.draw do
  resources :recipes, :has_many => :steps
  resources :steps, :belongs_to => :recipes

  resources :recipes do
    resources :steps
  end

  resources :plugin_calls do
    resources :steps
  end

  resources :plugin_calls do
    resources :plugin_call_fields
  end

  resources :plugin_call_fields

  resources :form_handlers

  root to: "recipes#create"

end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  attr_accessible :name, :description
  has_many :steps
  has_many :plugin_calls, through: :steps
  accepts_nested_attributes_for :steps, allow_destroy: true
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: [:show, :edit, :update, :destroy]



  def index
    @recipes = Recipe.all
  end

  def show
    @recipe = Recipe.find(params[:id])
    @steps = @recipe.steps

    if @recipe.steps.length == 0
      redirect_to new_step_path(recipe: @recipe)
    end

  end

  def new
    @recipe = Recipe.new
    @recipe.steps.build
  end

  def edit

  end



  def create

   @recipe = Recipe.new(:name => "Analysis Sequence", :description => "")

    respond_to do |format|

      if @recipe.save
        view_context.newrecipe(@recipe.id)
        format.html { redirect_to @recipe}
        format.json { render action: 'show', status: :created, location: @recipe }
      else
       format.html { render action: 'new' }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end

  end

  def update
    if @recipe.update(recipe_params)
      redirect_to @recipe, notice: 'Recipe was successfully updated.'
    else
      render action: 'edit'
    end
  end

  def destroy
    @recipe.destroy
    respond_to do |format|
      format.html { redirect_to :root, notice: 'Analysis Sequence was successfully deleted.' }
      format.json { head :no_content }
      format.js   {}
    end
    redirect_to recipes_path
  end

  private
    def set_recipe
      @recipe = Recipe.find(params[:id])

    end

    def recipe_params
      params.require(:recipe).permit(:name, :description, steps_attributes: [:id, :name, :description, :number, :plugin_call_id, :recipe_id, :docfile, :_destroy])
    end
end

app/views/recipes/_choropleth.html.erb
<%= javascript_include_tag 'datamaps.world.min' %>

<div id="container" style="position: relative; width: 1000px; height:
			   600px;"></div>
<script>
    var dataset;
    var filldata;
    d3.json(<%= raw output %>, function(error, data){
    dataset = data;
    
    var choropleth = new Datamap({
      element: document.getElementById('container'),
      projection: 'mercator',
      fills: {
        defaultFill: "#ABDDA4"
      }
    });
    
    choropleth.updateChoropleth(dataset);
});
</script>

app/views/recipes/_datatable.html.erb
<table>
<tr><td>
<div id="<%= stepnum %>datatable" class="collapse in">
  <a href="<%= url = '../'+stepnum.to_s+'step'+@recipe.id.to_s+'.json' %>">Download Data</a>
  <%= raw output %>
</div>
</td>
</tr>
</table>

app/views/recipes/_emailtimeline.html.erb
    <head>


      <!-- jQuery -->



        <!-- BEGIN TimelineJS -->
        <script type="text/javascript">
            jQuery(document).ready(function($) {
                createStoryJS({
                    type:       'timeline',
                    width:      '800',
                    height:     '600',
                    start_zoom_adjust:  '1',
                    start_at_end:       false,
                    source: <%= raw output %>,
                    embed_id:   'time_line'
                });

            });
        </script>
        <!-- END TimelineJS -->
    </head>
    <body>

        <div id="time_line"></div>

    </body>

app/views/recipes/_form.html.erb
<%= form_for @recipe do |f| %>
    <% f.fields_for :steps do |s| %>
        <%= s.grouped_collection_select :plugin_call_id, Plugin.where(category_id: 1).order(:name), :plugin_calls, :name, :id, :what, include_blank: 'Please select', wrapper_html: {class: 'medium-12 small-12 columns'} %>
        <%= hidden_field_tag :recipe_id, recipe.id %>
        <%= s.submit 'Next: Tool Inputs', :class => 'button modal-form' %>


  <div class="form-actions">
    <%= f.button :submit, :class => 'btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                recipes_path, :class => 'btn' %>
  </div>
        <% end %>
<% end %>

app/views/recipes/_jsontochart.html.erb
<%= raw output %>

app/views/recipes/_link.html.erb
<table>
<tr><td>
<div id="<%= stepnum %>datatable" class="collapse in">
  <a href="<%= url = '../'+stepnum.to_s+'step'+@recipe.id.to_s+'.json' %>">Download Data</a>
</div>
</td>
</tr>
</table>

app/views/recipes/_map.html.erb
<div id="map" style="height: 600px; width: 1000px;"></div>

<script>
  var map = L.map('map').setView(<%= raw output[1] %>, <%= raw output[2] %>);
  L.tileLayer('http://{s}.tile.osm.org/{z}/{x}/{y}.png', {
    attribution: '&copy; <a href="http://openstreetmap.org">OpenStreetMap</a> contributors', maxZoom: 18 }).addTo(map);

d3.json(<%= raw output[0] %>, function(error, data){
  var someFeatures = data;

  function onEachFeature(feature, layer) {
    // does this feature have a property named popupContent?
    if (feature.properties && feature.properties.popupContent) {
        layer.bindPopup(feature.properties.popupContent, {maxHeight: 200, closeButton: true});
    }
}

L.geoJson(someFeatures, {
        onEachFeature: onEachFeature
}).addTo(map);
});
</script>

app/views/recipes/_networkgraph.html.erb
<%= stylesheet_link_tag "network_graph" %>
<body>
  <div id="tooltip" class="hidden">
      <p><span id="content"></span></p>
    </div>
<div class="large-9 push-3 columns" id="chart">
<script type="text/javascript">
    var width = $('#chart').width();
    var height = $('#chart').height();
    var dataset;

    d3.selection.prototype.putOnTop = function(){
        return this.each(function(){
            this.parentNode.appendChild(this);
        });
    };
    d3.selection.prototype.putOnTopLinks = function(lline){
        return this.each(function(){
            this.parentNode.insertBefore(this, lline);
        });
    };

    d3.selection.prototype.putUnderneath = function(fnode){
        return this.each(function(){
            this.parentNode.insertBefore(this, fnode);
        });
    };

    var zoom = d3.behavior.zoom()
            .scaleExtent([1, 10])
            .on("zoom", function(){
                svg.attr("transform", "translate(" + d3.event.translate + ")scale(" + d3.event.scale + ")");
            });

    var svg = d3.select("div.large-9.push-3.columns")
            .append("svg")
            .attr("width", "100%")
            .attr("height", "100vh")
            .call(zoom);

    d3.json(<%= raw output %>, function(error, data){
        dataset = data;
        var nodecount = 0;

        var force = d3.layout.force()
                .nodes(data.nodes)
                .links(data.links)
                .size([width, height])
                .linkDistance([200])
                .charge([-200])
                .start();

        var node_drag = d3.behavior.drag()
                .on("dragstart", dragstart)
                .on("drag", dragmove)
                .on("dragend", dragend);

        function dragstart(d, i){
            d3.event.sourceEvent.stopPropagation();
            force.stop();
        }

        function dragmove(d, i){
            d.px += d3.event.dx;
            d.py += d3.event.dy;
            d.x += d3.event.dx;
            d.y += d3.event.dy;
            tick();
        }

        function dragend(d, i){
            d.fixed = true;
            tick();
            force.resume();
        }

        var links = svg.selectAll("line")
                .data(data.links.filter(function(d){
                    return d.lowestLinkCount > 0;
                }))
                .enter()
                .append("line")
                .style("stroke", "#ccc")
                .style("stroke-width", function(d){
                    if(d.data.length > 10){
                        var add = 11;
                    } else {
                        var add = d.data.length;
                    }
                    return add;
                });

        var nodes = svg.selectAll("circle")
                .data(data.nodes.filter(function(d){
                    return d.linkcount > 0;
                }))
                .enter()
                .append("circle")
                .attr("r", function(d){
                    if(d.data.length > 10){
                        var add = 11;
                    } else {
                        var add = d.data.length;
                    }
                    return 5 + add;
                })
                .style("fill", function(d){
                    if(d.type === <%= raw firstnode %>){
                        return "#0000CC";
                    } else {
                        return "#CC0000";
                    }
                })
                .style("stroke", "#000000")
                .style("stroke-width", 3)
                .attr("id", function(d){
                    return d.id;
                })
                .call(node_drag);


        nodes.on("mouseover", function(d){
            d3.select(this)
                    .style("stroke", "#E89619")
                    .putOnTop();

            links.filter(function(e){
                if((e.field1 == d.name) || (e.field2 == d.name)){
                    d3.select(this)
                            .style("stroke", "#E89619")
                            .putOnTopLinks(links[0][links[0].length-1])
                            .style("stroke-width", function(b){
                                if(b.data.length > 10){
                                    var add = 11;
                                } else {
                                    var add = b.data.length;
                                }

                                return add*2;
                            });

                    nodes.filter(function(f){
                        if((e.field1 == f.name) || (e.field2 == f.name)){
                            d3.select(this)
                                    .style("stroke", "#E89619")
                                    .putOnTop();
                        }
                    });
                    return e;
                }
            });

            d3.select("#tooltip")
                    .style("left", d3.event.pageX+"px")
                    .style("top", d3.event.pageY+"px")
                    .select("#content")
                    .text(d.name);

            d3.select("#tooltip")
                    .classed("hidden", false)
                    .putOnTop();
        })
                .on("mouseout", function(d){
                    d3.select(this)
                            .style("stroke", "#000000");

                    links.filter(function(e){
                        if((e.field1 == d.name) || (e.field2 == d.name)){
                            d3.select(this)
                                    .style("stroke", "#ccc")
                                    .putUnderneath(links[0][0])
                                    .style("stroke-width", function(b){
                                        if(b.data.length > 10){
                                            var add = 11;
                                        } else {
                                            var add = b.data.length;
                                        }

                                        return add;
                                    });

                            nodes.filter(function(f){
                                if((e.field1 == f.name) || (e.field2 == f.name)){
                                    d3.select(this)
                                            .style("stroke", "#000000");
                                }
                            });
                            return e;
                        }
                    });

                    d3.select("#tooltip").classed("hidden", true);
                })
                .on("click", function(d){
                    var output = "<h3>" + d.name + "</h3>";
                    for(var z = 0; z < d.data.length; z++){
                        output = output + "<dl>" + genItem(d, z) + "</dl>";
                    }

                    d3.select("#info")
                            .select("#gentext")
                            .html(output);
                    checkDuplicate = [];
                });

        // Generate items to show in sidebar and check for duplicates
        var checkDuplicate = [];
        function genItem(d, z){
            if(d.type == <%= raw firstnode %>){
                var title = d.data[z][<%= raw secondnode %>];
            } else {
                var title = d.data[z][<%= raw firstnode %>];
            }

            // Generate HTML for each item
            var item = "";

            for(var a in d.data[z]){
                var label = "<dt>" + a + ": " + "</dt>";
                item = item + label + "<dd>" + d.data[z][a] + "</dd>";
            }

            if(!deDuplicate(item)){
                return "<h4>" + title + "</h4>" + item + "<br />";
            } else {
                return "";
            }
        }

        // Checks items for duplicates
        function deDuplicate(item){
            for(var j = 1; j <= checkDuplicate.length; j++){
                if(checkDuplicate[j] === item){
                    return true;
                }
            }
            checkDuplicate.push(item);
            return false;
        }

        $(document).ready(function(){
            $("#search").keyup(function(){
                var searchterm = $(this).val();
                var output = "";
                nodes.filter(function(d){
                    for(var z = 0; z < d.data.length; z++){
                        var foundflag = 0;
                        for(var a in d.data[z]){
                            if(d.data[z][a]){
                                if((d.data[z][a].toString()).search(new RegExp(searchterm, "i")) != -1){
                                    foundflag = 1;
                                }
                            }
                        }

                        if(foundflag == 1 && searchterm.length > 2){
                            if(d["name"].toUpperCase() === searchterm.toUpperCase()){
                                d3.select(this)
                                        .style("fill", "#00CC00");
                            } else {
                                d3.select(this)
                                        .style("fill", "#E89619");
                            }
                            output = output + genItem(d, z);
                        } else {
                            d3.select(this)
                                    .style("fill", function(g){
                                        if(g.type == <%= raw firstnode %>){
                                            return  "#0000CC";
                                        } else {
                                            return "#CC0000";
                                        }
                                    });
                        }
                    }
                });

                if(output != ("")){
                    d3.select("#info")
                            .select("#gentext")
                            .html("<h3>" + searchterm + "</h3>" + output);
                    checkDuplicate = [];
                }
            });

        });

        function collide(a){
            var quadtree = d3.geom.quadtree(nodes);
            return function(d){
                if(d.linkcount > 10){
                    var radius = 11;
                } else {
                    var radius = d.linkcount;
                }
                var maxRadius = 11;
                var padding = 1.5;
                var r = radius + maxRadius + padding;
                var nx1 = d.x - r,
                        nx2 = d.x + r,
                        ny1 = d.y - r,
                        ny2 = d.y + r;

                quadtree.visit(function(quad, x1, y1, x2, y2){
                    if(quad.point && (quad.point !== d)){
                        var x = d.x - quad.point.x,
                                y = d.y - quad.point.y,
                                l = Math.sqrt(x*x+y*y);

                        if(quad.point.linkcount > 10){
                            var quadradius = 11;
                        } else {
                            var quadradius = quad.point.linkcount;
                        }

                        r = radius + quadradius;

                        if(l < r){
                            l = (l-r) / l*a;
                            d.x -= x *= l;
                            d.y -= y *= l;
                            quad.point.x += x;
                            quad.point.y += y;
                        }
                    }
                    return x1 > nx2 || x2 < nx1 || y1 > ny2 || y2 < ny1;
                });
            };
        }

        force.on("tick", tick);
        function tick() {
            links.attr("x1", function(d) { return d.source.x; })
                    .attr("y1", function(d) { return d.source.y; })
                    .attr("x2", function(d) { return d.target.x; })
                    .attr("y2", function(d) { return d.target.y; });

            nodes.each(collide(.5))
                    .attr("cx", function(d) { return d.x; })
                    .attr("cy", function(d) { return d.y; });
        }
    });
</script>
</div>
<div class="large-3 pull-9 columns" id="info">
  <aside class="sidebar">

    <form>
    <input type="text" id="search" name="search" placeholder="Search" tabindex="1">
     </form>
    <p id="gentext"></p>
  </aside>
</div>

</body>

app/views/recipes/_upload.html.erb
<a href="<%= url = '../'+stepnum.to_s+'step'+@recipe.id.to_s+'.json' %>">Download Data</a><br />
<%= JSON.parse(output) %>

app/views/recipes/_uploadsingle.html.erb
<%= raw output %>

app/views/recipes/_wordcloud.html.erb
<%= raw output %>

app/views/recipes/index.html.erb
<%- model_class = Recipe -%>
<div class="page-header">
  <h1>Analysis Tool Recipes</h1>
</div>

<p>To use the analysis tools, click "New" to make a new recipe. Then add the
  steps of the analysis on the next page</p>

<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @recipes.each do |recipe| %>
      <tr>
        <td><%= link_to recipe.name, recipe_path(recipe) %></td>
        <td><%= recipe.description %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_recipe_path(recipe), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      recipe_path(recipe),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_recipe_path,
            :class => 'btn btn-primary' %>

app/views/recipes/new.html.erb
<div class="row" data-equalizer>

  <div class="medium-4 small-4 columns callout panel" data-equalizer-watch>
    <dl>
      <dt>
        Get Data
      </dt>
      <dd>
        Get data from a variety of sources or upload your own documents.
      </dd>
    </dl>
    <span data-tooltip class="has-tip" title="Click here to get or upload data."><a href="#" class="button" data-reveal-id="getDataModal" data-reveal>Get Data</a></span>
  </div>
  <div class="medium-4 small-4 columns
    <% if @recipe.nil? %>
      <% else %>  callout <% end %> panel" data-equalizer-watch>
    <dl>
      <dt>
        Combine/Filter
      </dt>
      <dd>
        Combine, crossreference, and extract text from documents and data.
      </dd>
    </dl>
    <span data-tooltip class="has-tip" title="Click here to combine data."><a href="#" class="button" data-reveal-id="combineDataModal" data-reveal>Combine/Filter</a></span>
  </div>
  <div class="medium-4 small-4 columns   <% if @recipe.nil? %>
      <% else %> callout <% end %> panel" data-equalizer-watch>
    <dl>
      <dt>
        Visualize
      </dt>
      <dd>
        Turn data and documents into visualizations like timelines and network graphs.
      </dd>
    </dl>
    <span data-tooltip class="has-tip" title="Click here to visualize data."><a href="#" class="button" data-reveal-id="visualizeDataModal" data-reveal>Visualize</a></span>

  </div>
</div>

<div id="getDataModal" class="reveal-modal" data-reveal>
  <%= render :partial => "steps/form", :locals => { :recipe => @recipe } %>
  <a class="close-reveal-modal">&#215;</a>
</div>
<div id="combineDataModal" class="reveal-modal" data-reveal>
  <%= render :partial => "steps/combineform", :locals => { :recipe => @recipe } %>
  <a class="close-reveal-modal">&#215;</a>
</div>
<div id="visualizeDataModal" class="reveal-modal" data-reveal>
  <%= render :partial => "steps/visualizeform", :locals => { :recipe => @recipe } %>
  <a class="close-reveal-modal">&#215;</a>
</div>


<script>
    $('.disabled').click(function(e){
        return false;
    });
</script>

app/views/recipes/show.html.erb
<div class="row">
  <div class="medium-12 small-12 clearfix">
    <h1 class="left">Current Recipe</h1>

    <%= link_to 'Delete', recipe_path(@recipe), method: :delete, data: {confirm: 'Are you sure?'}, class: 'large button alert right' %>
  </div>

</div>
<div class="row">
  <div class="medium-12 small-12">
  <p>
     This is when you can view the output of the tools in this recipe, or add new tools to the recipe sequence.
      To add a new tool, click "Use Another Tool", or if you'd like to edit currently active tools, Click the "Edit" tab
      underneath it.
      Then fill in any settings or inputs for the tool. The output will be displayed under each step in the "Details"
      tab.

  </p>
  </div>
</div>

<div class="row">
  <dl class="accordion" data-accordion>
    <% @steps.order(:number).each do |step| %>

        <dd class="outer">

          <a href="#panel<%= step.number %>" class="title" > Step <%= step.number%></a>

          <div id="panel<%= step.number %>" class="content <% if step.number =='1' %>active<%else%><%end%>">
            <dl class="tabs" data-tab data-options=deep_linking:true">
              <dd><a href="#panel<%= step.number  %>-<%= step.id %>">Details</a></dd>
              <dd><a href="#panel<%= step.number %>-<%= step.id + 1  %>">Edit</a></dd>
            </dl>
            <div class="tabs-content">
              <div class="content <% if step.number %>active<% else %><% end %>" id="panel<%= step.number %>-<%= step.id %>">

                <%= switchView(step.plugin_call_id.to_i, step.properties,
                               step.number.to_i, @recipe.id.to_i) %>

                <%= link_to 'Show Fullscreen', recipe_step_path(@recipe, step), :target => "_blank", :class => 'button secondary'%>





              </div>
              <div class="content" id="panel<%= step.number  %>-<%= step.id + 1 %>">
                <%= render :partial => "steps/editform", :locals => {:step => step} %>
              </div>


            </div>


          </div>

        </dd>


    <% end %>
  </dl>

</div>
<div class="row">
  <div class="medium-12 small-12">
    <%= link_to "Use Another Tool", new_recipe_step_path(@recipe), :class => "button" %>

  </div>
</div>

<script>
    jQuery.noConflict();
    Foundation.utils.S(".accordion a").on('click',function(){
        Foundation.utils.S("dd.active a").children('.fi-arrows-compress, .fi-arrows-expand').toggleClass("fi-arrows-compress fi-arrows-expand");
        Foundation.utils.S(this).children('.fi-arrows-compress, .fi-arrows-expand').toggleClass("fi-arrows-compress fi-arrows-expand");
    });

    Foundation.utils.S(document).on('click', '.accordion .title', function(ev) {
        if (Foundation.utils.S(this).next('.content').find('.storyjs-embed sized-embed').length > 0) {
            Foundation.utils.S(window).resize();
        }
    });







</script>