config/routes.rb
Inputtest2::Application.routes.draw do
  resources :recipes, :has_many => :steps
  resources :steps, :belongs_to => :recipes

  resources :recipes do
    resources :steps
  end

  resources :plugin_calls do
    resources :steps
  end

  resources :plugin_calls do
    resources :plugin_call_fields
  end

  resources :plugin_call_fields

  resources :form_handlers

  root to: "recipes#create"

end

app/controllers/plugins_controller.rb
require 'tempfile'
require 'fileutils'

class PluginsController < ApplicationController
  before_action :set_plugin, only: [:show, :edit, :update, :destroy]

  # GET /plugins
  # GET /plugins.json
  def index
    @plugins = Plugin.all
  end

  # GET /plugins/1
  # GET /plugins/1.json
  def show
  end

  # GET /plugins/new
  def new
    @plugin = Plugin.new
  end

  # GET /plugins/1/edit
  def edit
  end

  # POST /plugins
  # POST /plugins.json
  def create
    @plugin = Plugin.new(plugin_params)
    #addplugin(@plugin.gemname)

    respond_to do |format|
      if @plugin.save
        format.html { redirect_to @plugin, notice: 'Plugin was successfully created.' }
        format.json { render action: 'show', status: :created, location: @plugin }
      else
        format.html { render action: 'new' }
        format.json { render json: @plugin.errors, status: :unprocessable_entity }
      end
    end
  end

  def addplugin(pluginname)
    file = File.open("Gemfile", "a+")
    file.puts "gem '" + pluginname + "'"
    system("sudo gem install " + pluginname)
  end

  # PATCH/PUT /plugins/1
  # PATCH/PUT /plugins/1.json
  def update
    respond_to do |format|
      if @plugin.update(plugin_params)
        format.html { redirect_to @plugin, notice: 'Plugin was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @plugin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /plugins/1
  # DELETE /plugins/1.json
  def destroy
    @plugin.destroy
    respond_to do |format|
      format.html { redirect_to plugins_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_plugin
      @plugin = Plugin.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def plugin_params
      params.require(:plugin).permit(:name, :description, :gemname, :method, :step_id)
    end
end

app/views/plugins/_form.html.erb
<%= form_for @plugin, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :description, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :description, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :gemname, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :gemname, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :method, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :method, :class => 'text_field' %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :category, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :category, :class => 'text_field' %>
    </div>
  </div>


  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                plugins_path, :class => 'btn' %>
  </div>
<% end %>

app/views/plugins/edit.html.erb
<%- model_class = Plugin -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/plugins/index.html.erb
<%- model_class = Plugin -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th><%= model_class.human_attribute_name(:gemname) %></th>
      <th><%= model_class.human_attribute_name(:method) %></th>
      <th><%= model_class.human_attribute_name(:step_id) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @plugins.each do |plugin| %>
      <tr>
        <td><%= link_to plugin.id, plugin_path(plugin) %></td>
        <td><%= plugin.name %></td>
        <td><%= plugin.description %></td>
        <td><%= plugin.gemname %></td>
        <td><%= plugin.method %></td>
        <td><%= plugin.step_id %></td>
        <td><%=l plugin.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_plugin_path(plugin), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      plugin_path(plugin),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>


<%= link_to t('.new', :default => t("helpers.links.new")),
            new_plugin_path,
            :class => 'btn btn-primary' %>

app/views/plugins/new.html.erb
<%- model_class = Plugin -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/plugins/show.html.erb
<%- model_class = Plugin -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @plugin.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= @plugin.description %></dd>
  <dt><strong><%= model_class.human_attribute_name(:gemname) %>:</strong></dt>
  <dd><%= @plugin.gemname %></dd>
  <dt><strong><%= model_class.human_attribute_name(:method) %>:</strong></dt>
  <dd><%= @plugin.method %></dd>
  <dt><strong><%= model_class.human_attribute_name(:step_id) %>:</strong></dt>
  <dd><%= @plugin.step_id %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              plugins_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_plugin_path(@plugin), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              plugin_path(@plugin),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>

<%= render :partial => "plugin_calls/plugin_call", :locals => { :plugin => @plugin } %>