config/routes.rb
Inputtest2::Application.routes.draw do
  resources :recipes, :has_many => :steps
  resources :steps, :belongs_to => :recipes

  resources :recipes do
    resources :steps
  end

  resources :plugin_calls do
    resources :steps
  end

  resources :plugin_calls do
    resources :plugin_call_fields
  end

  resources :plugin_call_fields

  resources :form_handlers

  root to: "recipes#create"

end

app/models/step.rb
class Step < ActiveRecord::Base
attr_accessible :description, :name, :number, :properties, :plugin_call_id, :docfile, :recipe_id
belongs_to :recipe,  inverse_of:  :steps
belongs_to :plugin_call, inverse_of: :steps
serialize :properties, Hash
mount_uploader :docfile, DocfileUploader
end

app/controllers/steps_controller.rb
class StepsController < ApplicationController
  before_filter :set_recipe, :only => [:index, :show, :new, :edit, :create, :update, :destroy]
  skip_before_action :set_step, only: [:file]
  before_action :set_step, only: [:show, :edit, :update, :destroy]



  def index

    @recipe = Recipe.find(params[:recipe_id])
    @step = @recipe.steps

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @steps }
    end
  end

  def new
    @recipe = Recipe.find(params[:recipe])
    @step = @recipe.steps.build(plugin_call_id: params[:plugin_call_id])
    @plugincalls = PluginCall.all
  end

  def edit
    @recipe = Recipe.find(params[:recipe_id])
    @step = @recipe.steps.find(params[:id])
  end

  def create
    @recipe = Recipe.find(params[:recipe_id])
    @step = @recipe.steps.create(params[:step_params])

    respond_to do |format|
      if @step.save
        session[:step_id] = @step.id
        redirect_to(controller: 'form_handlers', stepid: @step.to_param, recipeid: @recipe.to_param)
     else
        format.html { render action: "new" }
        format.json { render json: @step.errors, status: :unprocessable_entity }
      end
    end
  end

  def show
    @recipe = Recipe.find(params[:recipe_id])
    @step = @recipe.steps.find(params[:id])



  end

  def update
    @recipe = Recipe.find(params[:recipe_id])
    @step = @recipe.steps.find(params[:id])
    respond_to do |format|
      if @step.update_attributes(params[:step])
        format.html { redirect_to([@step.recipe, @step], :notice => 'Step was successfully updated.') }
        format.xml  { head :ok }

      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @step.errors, :status => :unprocessable_entity }

      end

    end
  end

  def destroy
    @step = @recipe.steps.find(params[:id])
    @step.destroy

    respond_to do |format|
      format.html { redirect_to(recipe_steps_url) }
      format.xml  { head :ok }
    end
  end




  private

  def set_recipe
    @recipe = Recipe.find(params[:recipe])
  end


  def set_step
      @step = Step.find(params[:id])
  end

  def current_step
    @_current_step ||= session[:step_id] &&
        Step.find_by(id: session[:step_id])
  end

    def step_params
      params.require(:step).permit(:name, :description, :number, :plugin_call_id, :recipe_id, :docfile).tap do |whitelisted|
        whitelisted[:properties] = params[:step][:properties]
      end
    end
end

app/helpers/steps_helper.rb
$recipehash = Hash.new

module StepsHelper

# Adds recipe to hash and makes object for tool data
def newrecipe(recipeid)
  $recipehash[recipeid] = PluginSaver.new(recipeid)
end

# Sets the step number
def setnum(recipeid)
  return $recipehash[recipeid].getlastnum + 1
end

# Returns preset array for dropdown
def getpreset(type)
  presetarray = Array.new
  
  # Go through govsites data
  if type === "govsites"
    sites = JSON.parse(File.read("public/sites.json"))
    sites["data"].each do |d|
      presetarray.push(d[8])
    end
  elsif type === "emails"
    presetarray = ["All Formats","firstname.lastname@domain","firstinitiallastname@domain","firstname_lastname@domain","lastnamefirstinitial@domain","lastname@domain"]
  end

  return presetarray
end

# Returns array of fields in JSON from last step
def getfields(recipeid)
  if ($recipehash[recipeid]) != nil && ($recipehash[recipeid].getlastnum != 0)
    $recipehash[recipeid].useobject($recipehash[recipeid].getlastnum)
    data = JSON.parse($recipehash[recipeid].getoutput($recipehash[recipeid].getlastnum))
    fields = Set.new

    data.map { |o| fields.merge(o.keys) }

    return fields
  end
end

# Returns an array with details on all previous steps in recipe
def getsteps(recipeid)
  if ($recipehash[recipeid]) != nil && ($recipehash[recipeid].getlastnum != 0)
    lastnum = $recipehash[recipeid].getlastnum
    steparray = Array.new
    
    (1..lastnum).each do |n|
      step = Step.where(number: n.to_s, inrecipe: recipeid).take
      plugin = PluginCall.find(step.plugin_call_id).what
      steparray.push(n.to_s + ". " + step.name + " (Tool: " + plugin + ")")
    end

    return steparray
  end
end

# Switches between tools
def switchTool(usedmethod, input=nil, stepnum, recipeid)
  if input == {} && $recipehash[recipeid].useobject(stepnum-1)
    input = $recipehash[recipeid].getoutput(stepnum-1)
  end
 
  if usedmethod == 15
    input = @step.docfile.to_s
  end

  case usedmethod
    when 13 then $recipehash[recipeid].addstep(stepnum, TimelinegenPlugin.new(usedmethod, input, stepnum, $recipehash[recipeid].getoutput(stepnum-1)))
    when 1..8 then $recipehash[recipeid].addstep(stepnum, SunlightcongressPlugin.new(usedmethod, input, stepnum, recipeid))
    when 9 then $recipehash[recipeid].addstep(stepnum, SunlightpartytimePlugin.new(usedmethod, input, stepnum, recipeid))
    when 11 then $recipehash[recipeid].addstep(stepnum, JsoncombinerPlugin.new(usedmethod, input, stepnum, recipeid))
    when 10 then $recipehash[recipeid].addstep(stepnum, LinkedindataPlugin.new(usedmethod, input, stepnum, recipeid))
    when 14 then $recipehash[recipeid].addstep(stepnum, WordcloudPlugin.new(usedmethod, input, stepnum))
    when 12 then $recipehash[recipeid].addstep(stepnum, JsoncrossreferencePlugin.new(usedmethod, input, stepnum, recipeid))
    when 15 then $recipehash[recipeid].addstep(stepnum, UploadPlugin.new(usedmethod, input, stepnum, recipeid))
    when 16 then $recipehash[recipeid].addstep(stepnum, EffscraperPlugin.new(usedmethod, input, stepnum, recipeid))
    when 17 then $recipehash[recipeid].addstep(stepnum, AcluscraperPlugin.new(usedmethod, input, stepnum, recipeid))
    when 18 then $recipehash[recipeid].addstep(stepnum, ExtractPlugin.new(usedmethod, input, stepnum, $recipehash[recipeid].getoutput(stepnum-1)))
    when 19 then $recipehash[recipeid].addstep(stepnum, WlsearchscraperPlugin.new(usedmethod, input, stepnum, recipeid))
    when 20 then $recipehash[recipeid].addstep(stepnum, LinkedindataPlugin.new(usedmethod, input, stepnum, recipeid))
    when 21 then $recipehash[recipeid].addstep(stepnum, NetworkgraphPlugin.new(usedmethod, input, stepnum, $recipehash[recipeid].getoutput(stepnum-1), recipeid))
    when 22..25 then $recipehash[recipeid].addstep(stepnum, GeneralscraperPlugin.new(usedmethod, input, stepnum, recipeid))
    when 26 then $recipehash[recipeid].addstep(stepnum, UnvoterecordsPlugin.new(usedmethod, input, stepnum, recipeid))
    when 27..29 then $recipehash[recipeid].addstep(stepnum, SpyfilesPlugin.new(usedmethod, input, stepnum, recipeid))
    when 30..31 then $recipehash[recipeid].addstep(stepnum, ExtractPlugin.new(usedmethod, input, stepnum, $recipehash[recipeid].getoutput(stepnum-1), recipeid))
    when 32 then $recipehash[recipeid].addstep(stepnum, ArchiverPlugin.new(usedmethod, input, stepnum, recipeid, nil))
    when 33 then $recipehash[recipeid].addstep(stepnum, ArchiverPlugin.new(usedmethod, input, stepnum, recipeid, $recipehash[recipeid].getoutput(stepnum-1)))
    when 34..35 then $recipehash[recipeid].addstep(stepnum, IndeedscraperPlugin.new(usedmethod, input, stepnum, recipeid))
    when 36 then $recipehash[recipeid].addstep(stepnum, ArchiverPlugin.new(usedmethod, input, stepnum, recipeid, $recipehash[recipeid].getoutput(stepnum-1)))
    when 37..43 then $recipehash[recipeid].addstep(stepnum, PrescrapedPlugin.new(usedmethod, input, stepnum, recipeid))
    when 44 then $recipehash[recipeid].addstep(stepnum, TordataPlugin.new(usedmethod, input, stepnum, recipeid))
    when 45 then $recipehash[recipeid].addstep(stepnum, TtcalcPlugin.new(usedmethod, input, stepnum, recipeid, $recipehash[recipeid].getoutput(stepnum-1)))
    when 46 then $recipehash[recipeid].addstep(stepnum, TotalinternetusersPlugin.new(usedmethod, input, stepnum, recipeid))
    when 47 then $recipehash[recipeid].addstep(stepnum, ChoroplethPlugin.new(usedmethod, input, stepnum, $recipehash[recipeid].getoutput(stepnum-1), recipeid))
    when 48 then $recipehash[recipeid].addstep(stepnum, TordataPlugin.new(usedmethod, input, stepnum, recipeid))
    when 49 then $recipehash[recipeid].addstep(stepnum, ChoroplethPlugin.new(usedmethod, input, stepnum, $recipehash[recipeid].getoutput(stepnum-1), recipeid))
    when 50 then $recipehash[recipeid].addstep(stepnum, PopulationPlugin.new(usedmethod, input, stepnum, recipeid))
    when 51 then $recipehash[recipeid].addstep(stepnum, MapPlugin.new(usedmethod, input, stepnum, $recipehash[recipeid].getoutput(stepnum-1), recipeid))
    when 52 then $recipehash[recipeid].addstep(stepnum, TtcalcPlugin.new(usedmethod, input, stepnum, recipeid, $recipehash[recipeid].getoutput(stepnum-1)))
  when 53..56 then $recipehash[recipeid].addstep(stepnum, NametoemailPlugin.new(usedmethod, input, stepnum, recipeid, $recipehash[recipeid].getoutput(stepnum-1)))
    else "Unknown Tool"
  end

  $recipehash[recipeid].useobject(stepnum).switch
end

# Switches between the views for different tools
def switchView(usedmethod, input=nil, stepnum, recipeid)
  case usedmethod
  when 13
    render :partial => 'recipes/emailtimeline', :locals => { :output => $recipehash[recipeid].getoutput(stepnum) }
  when 1..10
    @j = JSONToChart.new($recipehash[recipeid].getoutput(stepnum), stepnum)
    render :partial => 'recipes/datatable', :locals => { :output => @j.table, :stepnum => stepnum }
  when 11
    render :partial => 'recipes/link', :locals => { :output => @output, :stepnum => stepnum }
  when 12
    @j = JSONToChart.new($recipehash[recipeid].getoutput(stepnum), stepnum)
    render :partial => 'recipes/datatable', :locals => { :output => @j.table, :stepnum => stepnum }
  when 14
    render :partial => 'recipes/wordcloud', :locals => { :output => $recipehash[recipeid].getoutput(stepnum) }
  when 15
    render :partial => 'recipes/uploadsingle', :locals => { :output => $recipehash[recipeid].getoutput(stepnum) }
  when 16
    render :partial => 'recipes/upload', :locals => { :output => $recipehash[recipeid].getoutput(stepnum), :stepnum => stepnum }
  when 17
    render :partial => 'recipes/upload', :locals => { :output => $recipehash[recipeid].getoutput(stepnum), :stepnum => stepnum }
  when 18
    @j = JSONToChart.new($recipehash[recipeid].getoutput(stepnum), stepnum)
    render :partial => 'recipes/datatable', :locals => { :output => @j.table, :stepnum => stepnum }
  when 19
    render :partial => 'recipes/upload', :locals => { :output => $recipehash[recipeid].getoutput(stepnum), :stepnum => stepnum }
  when 20
    render :partial => 'recipes/link', :locals => { :path => "../nsadata.json" }
  when 21
    render :partial => 'recipes/networkgraph', :locals => { :output => $recipehash[recipeid].getoutput(stepnum), :firstnode => $recipehash[recipeid].getnode(stepnum), :secondnode => $recipehash[recipeid].getothernode(stepnum) }
  when 22
    render :partial => 'recipes/upload', :locals => { :output => $recipehash[recipeid].getoutput(stepnum), :stepnum => stepnum }
  when 23
    @j = JSONToChart.new($recipehash[recipeid].getoutput(stepnum), stepnum)
    render :partial => 'recipes/datatable', :locals => { :output => @j.table, :stepnum => stepnum }
  when 24
    render :partial => 'recipes/upload', :locals => { :output => $recipehash[recipeid].getoutput(stepnum), :stepnum => stepnum }
  when 25
    @j = JSONToChart.new($recipehash[recipeid].getoutput(stepnum), stepnum)
    render :partial => 'recipes/datatable', :locals => { :output => @j.table, :stepnum => stepnum }
  when 26
    @j = JSONToChart.new($recipehash[recipeid].getoutput(stepnum), stepnum)
    render :partial => 'recipes/datatable', :locals => { :output => @j.table, :stepnum => stepnum }
  when 27..28
    @j = JSONToChart.new($recipehash[recipeid].getoutput(stepnum), stepnum)
    render :partial => 'recipes/datatable', :locals => { :output => @j.table, :stepnum => stepnum }
  when 29
    render :partial => 'recipes/upload', :locals => { :output => $recipehash[recipeid].getoutput(stepnum), :stepnum => stepnum }
  when 30..31
    @j = JSONToChart.new($recipehash[recipeid].getoutput(stepnum), stepnum)
    render :partial => 'recipes/datatable', :locals => { :output => @j.table, :stepnum => stepnum }
  when 32
    render :partial => 'recipes/upload', :locals => { :output => $recipehash[recipeid].getoutput(stepnum), :stepnum => stepnum }
  when 33..34
    @j = JSONToChart.new($recipehash[recipeid].getoutput(stepnum), stepnum)

app/views/steps/_editform.html.erb
<%= form_for step do |f| %>

      <div class="medium-8 small-8">
        <div class="row">
          <div class="medium-3 columns">
            <%= f.label :name, 'Name:', :class => 'right inline' %>
          </div>
          <div class="medium-9 columns">
            <%= f.text_field :name, :placeholder => 'What is this analysis step called?' %>
          </div>
        </div>
        <div class="row">
          <div class="medium-3 columns">
            <%= f.label :description, 'Description:"', :class => 'right inline' %>
          </div>
          <div class="medium-9 columns">
            <%= f.text_field :description, :placeholder => 'What does this step do?'%>
          </div>
        </div>
        <div class="row">
          <div class="medium-3 columns">
            <%= f.label :number, 'Number:', :class => 'right inline' %>
          </div>
          <div class="medium-9 columns">
            <%= f.text_field :number, :placeholder => 'How many steps are in the sequence?' %>

          </div>

        </div>
        <div class="row">
          <div class="medium-3 columns">
            <%= f.label :usedplugin, 'Tool:', :class => 'right inline' %>
          </div>
          <div class="medium-9 columns">
            <%= f.collection_select :usedplugin, Plugin.all, :id, :name, :prompt => 'Which tool do you want to use?' %>
          </div>

        </div>
        <div class="medium-6 small-centered columns">
            <ul class="button-group text-center">
              <li><%= f.submit 'Update', :class => 'button'%></li>
              <li><%= button_to 'destroy', step, :method => :delete %></li>

            </ul>

         </div>
      </div>


<% end %>

app/views/steps/_form.html.erb
<%= form_for(@step) do |f| %>


    <%= f.collection_select :plugin_call_id,  PluginCall.where(category: category).order(:id), :details, :what, include_blank: 'Please select', wrapper_html: {class: 'medium-12 small-12 columns'} %>

    <%= hidden_field_tag :recipe_id %>
    <%= f.submit 'Next: Tool Inputs', :class => 'button modal-form' %>
<% end %>

app/views/steps/_steps.html.erb
<div class="row">
<dl class="accordion" data-accordion>
  <% @recipe.steps.order(:number).each do |step| %>

      <dd class="outer">

        <a href="#panel<%= step.number %>" class="title" > Step <%= step.number%></a>

        <div id="panel<%= step.number %>" class="content <% if step.number =='1' %>active<%else%><%end%>">
          <dl class="tabs" data-tab data-options=deep_linking:true">
            <dd><a href="#panel<%= step.number  %>-<%= step.id %>">Details</a></dd>
            <dd><a href="#panel<%= step.number %>-<%= step.id + 1  %>">Edit</a></dd>
          </dl>
          <div class="tabs-content">
            <div class="content <% if step.number %>active<% else %><% end %>" id="panel<%= step.number %>-<%= step.id %>">

	      <% if (step.plugin_call_id.to_i != 21) %>
              <%= switchView(step.plugin_call_id.to_i, step.properties,
                             step.number.to_i, @recipe.id.to_i) %>
	      <% end %>

              <%= link_to 'Show Fullscreen', recipe_step_path(@recipe, step), :target => "_blank", :class => 'button secondary'%>





            </div>
            <div class="content" id="panel<%= step.number  %>-<%= step.id + 1 %>">
              <%= render :partial => "steps/editform", :locals => {:step => step} %>
            </div>


          </div>


        </div>

      </dd>


  <% end %>
</dl>

  </div>
<div class="row">
  <div class="medium-12 small-12">
    <%= link_to "Use Another Tool", new_step_path(recipe: recipe), :class => "button" %>

  </div>
</div>

<script>
    jQuery.noConflict();
    Foundation.utils.S(".accordion a").on('click',function(){
        Foundation.utils.S("dd.active a").children('.fi-arrows-compress, .fi-arrows-expand').toggleClass("fi-arrows-compress fi-arrows-expand");
        Foundation.utils.S(this).children('.fi-arrows-compress, .fi-arrows-expand').toggleClass("fi-arrows-compress fi-arrows-expand");
    });



    Foundation.utils.S('.content .active').on('toggled', function (event, tab) {
        Foundation.utils.S(window).trigger('resize');
    });
</script>

app/views/steps/_visualizeform.html.erb
<%= form_for [recipe, recipe.steps.build],  html: {:id => 'new_visualize_step'} do |f| %>
    <%= f.grouped_collection_select :plugin_call_id, Plugin.where(category_id: 3).order(:name), :plugin_calls, :name, :id, :what, include_blank: 'Please select', wrapper_html: {class: 'medium-12 small-12 columns'} %>
    <%= hidden_field_tag :inrecipe, recipe.id %>
    <%= f.submit 'Next: Tool Inputs', :class => 'close-reveal-modal button modal-form' %>
<% end %>

app/views/steps/new.html.erb
<div class="row" data-equalizer>

  <div class="large-4 columns callout panel" >
    <dl data-equalizer-watch>
      <dt> <h3>
        Get Data </h3>
      </dt>
      <dd class="description">
	Get data from a variety of sources or upload your own documents.
      </dd>
      <dd>
        <span data-tooltip class="has-tip" title="Click here to get or upload data."><a href="#" class="button large" data-reveal-id="getDataModal" data-reveal>Get Data</a></span>
      </dd>
    </dl>
  </div>
  <div class="large-4 columns
 callout panel" >
    <dl data-equalizer-watch>
      <dt> <h3>
        Combine/Filter </h3>
      </dt>
      <dd class="description">
	Combine, crossreference, and extract text from documents and data.
      </dd>
      <dd>
        <span data-tooltip class="has-tip" title="Click here to combine data."><a href="#" class="button large" data-reveal-id="combineDataModal" data-reveal>Combine/Filter</a></span>

      </dd>
    </dl>
  </div>
  <div class="large-4 columns
      callout  panel" >
    <dl data-equalizer-watch>
      <dt>    <h3>
        Visualize  </h3>
      </dt>
      <dd class="description">
	Turn data and documents into visualizations like timelines and network graphs. 
      </dd>
      <dd>
        <span data-tooltip class="has-tip" title="Click here to visualize data."><a href="#" class="button large" data-reveal-id="visualizeDataModal" data-reveal>Visualize</a></span>


      </dd>
    </dl>

  </div>
</div>

<div id="getDataModal" class="reveal-modal" data-reveal>
  <h3>Get New Data</h3>
  <%= render :partial => "steps/form", :locals => { :recipe => @recipe , :category => 'Get' } %>
  <a class="close-reveal-modal">&#215;</a>
</div>
<div id="combineDataModal" class="reveal-modal" data-reveal>
  <h3>Combine Data</h3>
  <%= render :partial => "steps/form", :locals => { :recipe => @recipe , :category => 'Combine'  } %>
  <a class="close-reveal-modal">&#215;</a>
</div>
<div id="visualizeDataModal" class="reveal-modal" data-reveal>
  <h3>Visualize Data</h3>
  <%= render :partial => "steps/form", :locals => { :recipe => @recipe , :category => 'Visualize'  } %>
  <a class="close-reveal-modal">&#215;</a>
</div>

app/views/steps/show.html.erb
<%= switchView(@step.plugin_call_id.to_i, @step.properties,
               @step.number.to_i, @step.recipe_id.to_i) %>